### ISSUE TITLE
Bluetooth devices disappearing on iOS

### ISSUE THREAD

**Issue by jrmilholland** [InvisibleWrench/FlutterMidiCommand#56]
On iOS (Android is fine) a device will not show in the list of devices on list refresh.

Device will initially show on connection using startScanningForBluetoothDevices, after connectToDevice and a successful connection, the device will disappear out of the list of available devices.

Connected device will still function as if it is still connected, but is not longer in the list of devices.

**Comment by jrmilholland** [comment]
Anyone else seeing this issue on iOS?

**Comment by mortenboye** [comment]
Fixed in 0.4.8

**Comment by mortenboye** [comment]
sorry, its up now

**Comment by upta** [comment]
No worries!  Is there normally a caching sort of delay with pub.dev packages? (I've never actually published one myself).

https://pub.dev/packages/flutter_midi_command is still showing 0.4.7 as the latest version for me so I wasn't sure if it normally takes a while to update.

**Comment by mortenboye** [comment]
Normally there’s not much delay, this looks like yet another human error.

**Comment by upta** [comment]
Hey @mortenboye I got a report that the devices are no longer disappearing on iOS which is awesome, thanks so much!

He also mentioned that it seems that devices are no longer showing up on MacOS with this version, do you have any thoughts on that?

Looking at the history, it seems that we were previously pointing to the "dev" branch, but are now pointing to "master" (for some reason 0.4.8 never ended up showing up on pub.dev so I just figured I'd point to master and get it that way).  Not sure if it's related, but I figured you'd have a lot more knowledge on the subject than I do 🙂

Thanks again for your help with all this!

**Comment by mortenboye** [comment]
0.4.8 should now finally be up on pub.dev 

I'm not seeing any issues on MacOS so if you can elaborate on what you are seeing or rather not seeing, that would be helpful.
